# -*- coding: utf-8 -*-
"""Number_gussing_Game.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ms3qs3rm1ZowbjNnLFuwK_FtDovqgInA
"""

import random

secret_number = random.randint(1, 100)

guess = int(input("Guess the number (1-100): "))

while guess != secret_number:

    if guess < secret_number:
        print("Too low!")
    else:
        print("Too high!")

    guess = int(input("Guess again: "))

print("Congratulations! You guessed the number.")

